[build]
builder = "nixpacks"
buildCommand = "go clean -modcache && go mod download && go build -o out ./cmd/server"

[deploy]
startCommand = "./out"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
